export const setPostStates = (data) => ({
  postID: data.postID,
  userID: data.userID,
  username: data.username,
  avatar: data.avatar,
  images: data.images,
  title: data.title,
  postText: data.postText,
  horseName: data.horseName,
  category: data.category,
  breed: data.breed,
  color: data.color,
  birth: {
    year: data.birth.year,
    month: data.birth.month,
    day: data.birth.day,
  },
  age: data.age,
  height: data.height,
  area: data.area,
  features: data.features,
  price: data.price,
  createdAt: data.createdAt,
  updatedAt: data.updatedAt,
  likeUserIDs: data.likeUserIDs,
  isAvairable: data.isAvairable,
  pv: data.pv,
  sendMessageUserIDs: data.sendMessageUserIDs,
  messageUpdatedAt: data.messageUpdatedAt,
  latestMessage: data.latestMessage,
  clientUserID: data.clientUserID,
});

export const setChatroomStates = (data) => ({
  sendUserID: data.sendUserID,
  sendUserName: data.sendUserName,
  sendUserAvatar: data.sendUserAvatar,
  postUserID: data.postUserID,
  postID: data.postID,
  postImage: data.postImage,
  postTitle: data.postTitle,
  latestMessage: data.latestMessage,
  messageCount: data.messageCount,
  createdAt: data.createdAt,
  messageUpdatedAt: data.messageUpdatedAt,
});

export const setMessageStates = (data) => ({
  userID: data.userID,
  postID: data.postID,
  username: data.username,
  avatar: data.avatar,
  messageText: data.messageText,
  image: data.image,
  createdAt: data.createdAt,
  firstOnDate: data.firstOnDate,
  clientDecision: data.clientDecision,
  dealInterruption: data.dealInterruption,
  dealCompleted: data.dealCompleted,
  pleaseRate: data.pleaseRate,
  rateCompleted: data.rateCompleted,
});

export const setReviewStates = (data) => ({
  postID: data.postID,
  postUserID: data.postUserID,
  postTitle: data.postTitle,
  postImage: data.postImage,
  reviewerID: data.reviewerID,
  reviewerName: data.reviewerName,
  reviewerAvatar: data.reviewerAvatar,
  rating: data.rating,
  reviewText: data.reviewText,
  createdAt: data.createdAt,
});

export const setNotificationStates = (data) => ({
  postID: data.postID,
  postUserID: data.postUserID,
  sendUserID: data.sendUserID,
  receiveUserID: data.receiveUserID,
  sendMessageUserID: data.sendMessageUserID,
  image: data.image,
  avatar: data.avatar,
  text: data.text,
  createdAt: data.createdAt,
  checked: data.checked,
  toMessage: data.toMessage,
  toProfile: data.toProfile,
});
