export const setPostStates = (data) => ({
  postID: data.postID,
  userID: data.userID,
  username: data.username,
  avatar: data.avatar,
  images: data.images,
  title: data.title,
  postText: data.postText,
  horseName: data.horseName,
  category: data.category,
  breed: data.breed,
  color: data.color,
  birth: {
    year: data.birth.year,
    month: data.birth.month,
    day: data.birth.day,
  },
  age: data.age,
  height: data.height,
  area: data.area,
  features: data.features,
  price: data.price,
  createdAt: data.createdAt,
  updatedAt: data.updatedAt,
  likeUserIDs: data.likeUserIDs,
  isAvairable: data.isAvairable,
  pv: data.pv,
  sendMessageUser: [{ ID: data.ID, createdAt: data.createdAt }],
});
